name: Deploy Task Tracker to VM

on:
  push:
    branches:
      - main
      - staging

jobs:
  update_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Docker containers on GCP VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ibukun_o
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -x
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              cd /home/ibukun_o/assessments/prod || { echo "Directory /home/ibukun_o/assessments/prod not found!"; exit 1; }
            elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
              cd /home/ibukun_o/assessments/staging || { echo "Directory /home/ibukun_o/assessments/staging not found!"; exit 1; }
            else
              echo "Branch not deployable, skipping deployment."
              exit 0
            fi

            if [ ! -d .git ]; then
              echo "Error: Not a git repository!"
              exit 1
            fi

            git pull origin ${{ github.ref_name }}

            # Stopping all services
            sudo docker compose down

            # Rebuilding and starting all services including Prometheus and Grafana
            sudo docker compose up -d --build

            #restart Prometheus and Grafana 
            sudo docker restart prometheus
            sudo docker restart grafana
