name: Deploy Task Tracker to VM

on:
  push:
    branches:
      - main
      - staging

jobs:
  update_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Docker containers on GCP VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ibukun_o
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -x

            # Clone the repository into prod or staging directory depending on branch
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              # For prod branch
              cd /home/ibukun_o/assessments/prod || { echo "Directory /home/ibukun_o/assessments/prod not found!"; exit 1; }
            elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
              # For staging branch
              cd /home/ibukun_o/assessments/staging || { echo "Directory /home/ibukun_o/assessments/staging not found!"; exit 1; }
            else
              echo "Branch not deployable, skipping deployment."
              exit 0
            fi

            # Clone the repository 
            if [ ! -d .git ]; then
              echo "Cloning the repository into the environment directory"
              git clone https://github.com/ibukun-oyedeji/assessments.git .
            fi

            # Pull latest changes for the specific branch
            git pull origin ${{ github.ref_name }}

            # Rebuild and restart the containers
            sudo docker compose down
            sudo docker compose up -d --build
