name: Deploy Task Tracker to VM

on:
  push:
    branches:
      - main
      - staging

jobs:
  update_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Docker containers on GCP VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ibukun_o
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -x
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              cd ~/assessments-prod || { echo "Directory ~/assessments-prod not found!"; exit 1; }
            elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
              cd ~/assessments-staging || { echo "Directory ~/assessments-staging not found!"; exit 1; }
            else
              echo "Branch not deployable, skipping deployment."
              exit 0
            fi

            if [ ! -d .git ]; then
              echo "Error: Not a git repository!"
              exit 1
            fi

            git pull origin ${{ github.ref_name }}

          
            sudo docker compose down
           
            sudo docker compose up -d --build

            sudo docker restart prometheus
            sudo docker restart grafana
